#!/bin/bash
#------SCRIPT FOR AUTOMATIC DIRECT & ADJOINT CALCULATIONS AND GRADIENTS EVALUATION------#
#------CALCULATING DIRECT SOLUTION------#
mpirun -np 4 SU2_CFD automatica.cfg
SU2_SOL automatica.cfg
#------GENERATING NEW CONFIGURATION FILE FOR ADJOINT CALCULATIONS------#
sed automatica.cfg -e "3,75{
s/DIRECT/DISCRETE\_ADJOINT/
story/history\_adjoint/
}" > ADJOINT.cfg
#------RENAMING DIRECT SOLUTION FILE TO ALLOW FOR RECOGNITION BY ADJOINT SOLVER------#
cp restart_flow.dat solution_flow.dat
#------CALCULATING ADJOINT SOLUTION------#
SU2_CFD_AD ADJOINT.cfg
#------GENERATING NEW CONFIGURATION FILE FOR SENSITIVITY PROJECTION------#
sed ADJOINT.cfg -e "74{
s/history\_adjoint/history\_dot\_ad/
}" > DOT_AD.cfg
#------RENAMING ADJOINT SOLUTION FILE TO ALLOW FOR RECOGNITION BY ALGORITHMIC DIFFERENCIATOR------#
cp restart_adj_cd.dat solution_adj_cd.dat
#------GRADIENTS EVALUATION BY SURFACE SENSITIVITY PROJECTION INTO THE DESIGN SPACE------#
SU2_DOT_AD DOT_AD.cfg